version: '3.8'

services:
  app:
    build:
      context: . 
    ports:
      - "3000:3000"  
    # depends_on:
    #   - mysql 

  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - "3306:3306"  
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password  
  #     MYSQL_DATABASE: shopdb 
  #   volumes:
  #     - mysql_data:/var/lib/mysql 

# volumes:
#   mysql_data:
