version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "80:3000"
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aAbBcCdDeE
      MYSQL_DATABASE: shopDB
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
